-- AlterTable
ALTER TABLE "Appointment" ALTER COLUMN "date" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Patient" ALTER COLUMN "birthDate" DROP NOT NULL,
ALTER COLUMN "age" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Sale" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "quantity" DROP NOT NULL,
ALTER COLUMN "amount" DROP NOT NULL;
